### ISSUE TITLE
could you do a haxelib release please? it does not compile with 3.4.5 but its recommended by haxe compiler

### ISSUE THREAD

**Issue by sebpatu** [HaxeFoundation/record-macros#16]
Hello,
when we compile with haxe 3.4.5 lots of warnings recommend to use your lib.
but if we get the latests release with haxelib install the code does not compile.
only for a very obscure reason:
the code of this release is exactly the same than in haxe 3.4.5 std library except for two lines that are the reason of the compilation error:
HaxeToolkit\3.4.5\lib\record-macros/1,0,0-alpha/src/sys/db/RecordMacros.hx:785: characters 8-12 : Capture variables must be lower-case

the case OpIn: line but OpIn does not exist in haxe 3.4.5

to make the haxe 3.4.5 adoption easier, could you please release a lib version that is working fine with haxe 3.4.5 please? a perfect copy of the standard lib code without warnings, at least, or the latests code version, if its passing all tests.

thanks

**Comment by sebpatu** [comment]
sorry i made a mistake
